apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oom-listener-rolebinding
  namespace: "{{ .Values.namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oom-listener-role
subjects:
  - kind: ServiceAccount
    name: oom-listener
    namespace: "{{ .Values.namespace }}"
