apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: "{{ .Values.namespace }}"
  name: oom-listener-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["create"]
